Rails.application.routes.draw do
  get 'nogitops/index'
  get 'top/index'
  devise_for :nogimasas, controllers: {
    registrations: "nogimasas/registrations",
    sessions: "nogimasas/sessions"
  }
  post "/homes/guest_sign_in", to: "nogizakas#new_guest"
  
  get "nogitops", to: "nogitops#index"
  get "nogizakas/login_check"
  get "nogizakas/danger"
  get "nogizakas/privacy"
  root "nogizakas#login_check"

  get "posts", to: "posts#index"
  #2012
  get "posts/2012", to:"posts#two"
  get "posts/2012/konno", to:"posts#konno"
  get "posts/new_konno", to: "posts#new_konno"
  post "posts/new_konno", to: "posts#create_konno"
  get "posts/2012/zepptokyo", to:"posts#zepptokyo"
  get "posts/new_zepptokyo", to: "posts#new_zepptokyo"
  post "posts/new_zepptokyo", to: "posts#create_zepptokyo"
  #2013
  get "posts/2013", to:"posts#three"
  get "posts/2013/first", to:"posts#first"
  get "posts/new_first", to: "posts#new_first"
  post "posts/new_first", to: "posts#create_first"
  get "posts/2013/three_summer_sapporo", to:"posts#three_summer_sapporo"
  get "posts/new_three_summer_sapporo", to: "posts#new_three_summer_sapporo"
  post "posts/new_three_summer_sapporo", to: "posts#create_three_summer_sapporo"
  get "posts/2013/three_summer_fukuoka", to:"posts#three_summer_fukuoka"
  get "posts/new_three_summer_fukuoka", to: "posts#new_three_summer_fukuoka"
  post "posts/new_three_summer_fukuoka", to: "posts#create_three_summer_fukuoka"
  get "posts/2013/three_summer_osaka", to:"posts#three_summer_osaka"
  get "posts/new_three_summer_osaka", to: "posts#new_three_summer_osaka"
  post "posts/new_three_summer_osaka", to: "posts#create_three_summer_osaka"
  get "posts/2013/three_summer_nagoya", to:"posts#three_summer_nagoya"
  get "posts/new_three_summer_nagoya", to: "posts#new_three_summer_nagoya"
  post "posts/new_three_summer_nagoya", to: "posts#create_three_summer_nagoya"
  get "posts/2013/three_summer_tokyo", to:"posts#three_summer_tokyo"
  get "posts/new_three_summer_tokyo", to: "posts#new_three_summer_tokyo"
  post "posts/new_three_summer_tokyo", to: "posts#create_three_summer_tokyo"
  get "posts/2013/three_summer_final", to:"posts#three_summer_final"
  get "posts/new_three_summer_final", to: "posts#new_three_summer_final"
  post "posts/new_three_summer_final", to: "posts#create_three_summer_final"
  get "posts/2013/three_xmas", to:"posts#three_xmas"
  get "posts/new_three_xmas", to: "posts#new_three_xmas"
  post "posts/new_three_xmas", to: "posts#create_three_xmas"
  #2014
  get "posts/2014", to:"posts#four"
  get "posts/2014/second", to:"posts#second"
  get "posts/new_second", to: "posts#new_second"
  post "posts/new_second", to: "posts#create_second"
  get "posts/2014/four_under", to:"posts#four_under"
  get "posts/new_four_under", to: "posts#new_four_under"
  post "posts/new_four_under", to: "posts#create_four_under"
  get "posts/2014/four_summer_osaka", to:"posts#four_summer_osaka"
  get "posts/new_four_summer_osaka", to: "posts#new_four_summer_osaka"
  post "posts/new_four_summer_osaka", to: "posts#create_four_summer_osaka"
  get "posts/2014/four_summer_fukuoka", to:"posts#four_summer_fukuoka"
  get "posts/new_four_summer_fukuoka", to: "posts#new_four_summer_fukuoka"
  post "posts/new_four_summer_fukuoka", to: "posts#create_four_summer_fukuoka"
  get "posts/2014/four_summer_sendai", to:"posts#four_summer_sendai"
  get "posts/new_four_summer_sendai", to: "posts#new_four_summer_sendai"
  post "posts/new_four_summer_sendai", to: "posts#create_four_summer_sendai"
  get "posts/2014/four_summer_nagoya", to:"posts#four_summer_nagoya"
  get "posts/new_four_summer_nagoya", to: "posts#new_four_summer_nagoya"
  post "posts/new_four_summer_nagoya", to: "posts#create_four_summer_nagoya"
  get "posts/2014/four_summer_tokyo", to:"posts#four_summer_tokyo"
  get "posts/new_four_summer_tokyo", to: "posts#new_four_summer_tokyo"
  post "posts/new_four_summer_tokyo", to: "posts#create_four_summer_tokyo"
  get "posts/2014/four_under_second", to:"posts#four_under_second"
  get "posts/new_four_under_second", to: "posts#new_four_under_second"
  post "posts/new_four_under_second", to: "posts#create_four_under_second"
  get "posts/2014/four_under_xmas", to:"posts#four_under_xmas"
  get "posts/new_four_under_xmas", to: "posts#new_four_under_xmas"
  post "posts/new_four_under_xmas", to: "posts#create_four_under_xmas"
  get "posts/2014/four_xmas", to:"posts#four_xmas"
  get "posts/new_four_xmas", to: "posts#new_four_xmas"
  post "posts/new_four_xmas", to: "posts#create_four_xmas"

  #2015
  get "posts/2015", to:"posts#five"
  get "posts/2015/third", to:"posts#third"
  get "posts/new_third", to: "posts#new_third"
  post "posts/new_third", to: "posts#create_third"
  get "posts/2015/five_summer_sendai", to: "posts#five_summer_sendai"
  get "posts/new_five_summer_sendai", to: "posts#new_five_summer_sendai"
  post "posts/new_five_summer_sendai", to: "posts#create_five_summer_sendai"
  get "posts/2015/five_summer_nagoya", to: "posts#five_summer_nagoya"
  get "posts/new_five_summer_nagoya", to: "posts#new_five_summer_nagoya"
  post "posts/new_five_summer_nagoya", to: "posts#create_five_summer_nagoya"
  get "posts/2015/five_summer_hirosima", to: "posts#five_summer_hirosima"
  get "posts/new_five_summer_hirosima", to: "posts#new_five_summer_hirosima"
  post "posts/new_five_summer_hirosima", to: "posts#create_five_summer_hirosima"
  get "posts/2015/five_summer_fukuoka", to: "posts#five_summer_fukuoka"
  get "posts/new_five_summer_fukuoka", to: "posts#new_five_summer_fukuoka"
  post "posts/new_five_summer_fukuoka", to: "posts#create_five_summer_fukuoka"
  get "posts/2015/five_summer_osaka", to: "posts#five_summer_osaka"
  get "posts/new_five_summer_osaka", to: "posts#new_five_summer_osaka"
  post "posts/new_five_summer_osaka",to: "posts#create_five_summer_osaka"
  get "posts/2015/five_summer_tokyo", to: "posts#five_summer_tokyo"
  get "posts/new_five_summer_tokyo", to: "posts#new_five_summer_tokyo"
  post "posts/new_five_summer_tokyo", to: "posts#create_five_summer_tokyo"
  get "posts/2015/five_under_four", to: "posts#five_under_four"
  get "posts/new_five_under_four", to: "posts#new_five_under_four"
  post "posts/new_five_under_four", to: "posts#create_five_under_four"
  get "posts/2015/five_under_budo", to: "posts#five_under_budo"
  get "posts/new_five_under_budo", to: "posts#new_five_under_budo"
  post "posts/new_five_under_budo", to: "posts#create_five_under_budo"
  get "posts/2015/five_xmas", to: "posts#five_xmas"
  get "posts/new_five_xmas", to: "posts#new_five_xmas"
  post "posts/new_five_xmas", to: "posts#create_five_xmas"

  #2016
  get "posts/2016", to:"posts#six"
  get "posts/2016/seira", to: "posts#seira"
  get "posts/new_seira", to: "posts#new_seira"
  post "posts/new_seira", to: "posts#create_seira"
  get "posts/2016/six_under_tohoku", to: "posts#six_under_tohoku"
  get "posts/new_six_under_tohoku", to: "posts#new_six_under_tohoku"
  post "posts/new_six_under_tohoku", to: "posts#create_six_under_tohoku"
  get "posts/2016/maimai", to: "posts#maimai"
  get "posts/new_maimai", to: "posts#new_maimai"
  post "posts/new_maimai", to: "posts#create_maimai"
  get "posts/2016/six_summer_osaka", to: "posts#six_summer_osaka"
  get "posts/new_six_summer_osaka", to: "posts#new_six_summer_osaka"
  post "posts/new_six_summer_osaka", to: "posts#create_six_summer_osaka"
  get "posts/2016/six_summer_nagoya", to: "posts#six_summer_nagoya"
  get "posts/new_six_summer_nagoya", to: "posts#new_six_summer_nagoya"
  post "posts/new_six_summer_nagoya", to: "posts#create_six_summer_nagoya"
  get "posts/2016/six_summer_sendai", to: "posts#six_summer_sendai"
  get "posts/new_six_summer_sendai", to: "posts#new_six_summer_sendai"
  post "posts/new_six_summer_sendai", to: "posts#create_six_summer_sendai"
  get "posts/2016/six_summer_fukuoka", to: "posts#six_summer_fukuoka"
  get "posts/new_six_summer_fukuoka", to: "posts#new_six_summer_fukuoka"
  post "posts/new_six_summer_fukuoka", to: "posts#create_six_summer_fukuoka"
  get "posts/2016/six_summer_tokyo", to: "posts#six_summer_tokyo"
  get "posts/new_six_summer_tokyo", to: "posts#new_six_summer_tokyo"
  post "posts/new_six_summer_tokyo", to: "posts#create_six_summer_tokyo"
  get "posts/2016/six_under_tyugoku", to: "posts#six_under_tyugoku"
  get "posts/new_six_under_tyugoku", to: "posts#new_six_under_tyugoku"
  post "posts/new_six_under_tyugoku", to: "posts#create_six_under_tyugoku"
  get "posts/2016/six_senbatu_xmas", to: "posts#six_senbatu_xmas"
  get "posts/new_six_senbatu_xmas", to: "posts#new_six_senbatu_xmas"
  post "posts/new_six_senbatu_xmas", to: "posts#create_six_senbatu_xmas"
  get "posts/2016/six_under_xmas", to: "posts#six_under_xmas"
  get "posts/new_six_under_xmas", to: "posts#new_six_under_xmas"
  post "posts/new_six_under_xmas", to: "posts#create_six_under_xmas"

  #2017
  get "posts/2017", to:"posts#seven"
  get "posts/2017/univ", to: "posts#univ"
  get "posts/new_univ", to: "posts#new_univ"
  post "posts/new_univ", to: "posts#create_univ"
  get "posts/2017/fifth", to: "posts#fifth"
  get "posts/new_fifth", to: "posts#new_fifth"
  post "posts/new_fifth", to: "posts#create_fifth"
  get "posts/2017/under_tokyo", to: "posts#under_tokyo"
  get "posts/new_under_tokyo", to: "posts#new_under_tokyo"
  post "posts/new_under_tokyo", to: "posts#create_under_tokyo"
  get "posts/2017/sanki", to: "posts#sanki"
  get "posts/new_sanki", to: "posts#new_sanki"
  post "posts/new_sanki", to: "posts#create_sanki"
  get "posts/2017/seven_summer_tokyo", to: "posts#seven_summer_tokyo"
  get "posts/new_seven_summer_tokyo", to: "posts#new_seven_summer_tokyo"
  post "posts/new_seven_summer_tokyo", to: "posts#create_seven_summer_tokyo"
  get "posts/2017/seven_summer_sendai", to: "posts#seven_summer_sendai"
  get "posts/new_seven_summer_sendai", to: "posts#new_seven_summer_sendai"
  post "posts/new_seven_summer_sendai", to: "posts#create_seven_summer_sendai"
  get "posts/2017/seven_summer_osaka", to: "posts#seven_summer_osaka"
  get "posts/new_seven_summer_osaka", to: "posts#new_seven_summer_osaka"
  post "posts/new_seven_summer_osaka", to: "posts#create_seven_summer_osaka"
  get "posts/2017/seven_summer_nagoya", to: "posts#seven_summer_nagoya"
  get "posts/new_seven_summer_nagoya", to: "posts#new_seven_summer_nagoya"
  post "posts/new_seven_summer_nagoya", to: "posts#create_seven_summer_nagoya"
  get "posts/2017/seven_summer_nigata", to: "posts#seven_summer_nigata"
  get "posts/new_seven_summer_nigata", to: "posts#new_seven_summer_nigata"
  post "posts/new_seven_summer_nigata", to: "posts#create_seven_summer_nigata"
  get "posts/2017/seven_summer_final", to: "posts#seven_summer_final"
  get "posts/new_seven_summer_final", to: "posts#new_seven_summer_final"
  post "posts/new_seven_summer_final", to: "posts#create_seven_summer_final"
  get "posts/2017/seven_under_kyusyu", to: "posts#seven_under_kyusyu"
  get "posts/new_seven_under_kyusyu", to: "posts#new_seven_under_kyusyu"
  post "posts/new_seven_under_kyusyu", to: "posts#create_seven_under_kyusyu"
  get "posts/2017/seven_under_kinki", to: "posts#seven_under_kinki"
  get "posts/new_seven_under_kinki", to: "posts#new_seven_under_kinki"
  post "posts/new_seven_under_kinki", to: "posts#create_seven_under_kinki"

  #2018
  get "posts/2018", to:"posts#eight"
  get "posts/2018/ikoma", to: "posts#ikoma"
  get "posts/new_ikoma", to: "posts#new_ikoma"
  post "posts/new_ikoma", to: "posts#create_ikoma"
  get "posts/2018/under_tyubu", to: "posts#under_tyubu"
  get "posts/new_under_tyubu", to: "posts#new_under_tyubu"
  post "posts/new_under_tyubu", to: "posts#create_under_tyubu"
  get "posts/2018/sixth", to: "posts#sixth"
  get "posts/new_sixth", to: "posts#new_sixth"
  post "posts/new_sixth", to: "posts#create_sixth"
  get "posts/2018/eight_summer_fukuoka", to: "posts#eight_summer_fukuoka"
  get "posts/new_eight_summer_fukuoka", to: "posts#new_eight_summer_fukuoka"
  post "posts/new_eight_summer_fukuoka", to: "posts#create_eight_summer_fukuoka"
  get "posts/2018/eight_summer_osaka", to: "posts#eight_summer_osaka"
  get "posts/new_eight_summer_osaka", to: "posts#new_eight_summer_osaka"
  post "posts/new_eight_summer_osaka", to: "posts#create_eight_summer_osaka"
  get "posts/2018/eight_summer_nagoya", to: "posts#eight_summer_nagoya"
  get "posts/new_eight_summer_nagoya", to: "posts#new_eight_summer_nagoya"
  post "posts/new_eight_summer_nagoya", to: "posts#create_eight_summer_nagoya"
  get "posts/2018/eight_summer_sendai",to: "posts#eight_summer_sendai"
  get "posts/new_eight_summer_sendai", to: "posts#new_eight_summer_sendai"
  post "posts/new_eight_summer_sendai", to: "posts#create_eight_summer_sendai"
  get "posts/2018/under_hokkaido",to: "posts#under_hokkaido"
  get "posts/new_under_hokkaido", to: "posts#new_under_hokkaido"
  post "posts/new_under_hokkaido", to: "posts#create_under_hokkaido"
  get "posts/2018/eight_shanghai",to: "posts#eight_shanghai"
  get "posts/new_eight_shanghai", to: "posts#new_eight_shanghai"
  post "posts/new_eight_shanghai", to: "posts#create_eight_shanghai"
  get "posts/2018/waka",to: "posts#waka"
  get "posts/new_waka", to: "posts#new_waka"
  post "posts/new_waka", to: "posts#create_waka"
  get "posts/2018/under_kanto",to: "posts#under_kanto"
  get "posts/new_under_kanto", to: "posts#new_under_kanto"
  post "posts/new_under_kanto", to: "posts#create_under_kanto"

  #2019
  get "posts/2019", to:"posts#nine"
  get "posts/2019/nine_taipei",to: "posts#nine_taipei"
  get "posts/new_nine_taipei", to: "posts#new_nine_taipei"
  post "posts/new_nine_taipei", to: "posts#create_nine_taipei"
  get "posts/2019/seventh",to: "posts#seventh"
  get "posts/new_seventh", to: "posts#new_seventh"
  post "posts/new_seventh", to: "posts#create_seventh"
  get "posts/2019/misa",to: "posts#misa"
  get "posts/new_misa", to: "posts#new_misa"
  post "posts/new_misa", to: "posts#create_misa"
  get "posts/2019/sing_out",to: "posts#sing_out"
  get "posts/new_sing_out", to: "posts#new_sing_out"
  post "posts/new_sing_out", to: "posts#create_sing_out"
  get "posts/2019/nine_summer_nagoya",to: "posts#nine_summer_nagoya"
  get "posts/new_nine_summer_nagoya", to: "posts#new_nine_summer_nagoya"
  post "posts/new_nine_summer_nagoya", to: "posts#create_nine_summer_nagoya"
  get "posts/2019/nine_summer_fukuoka",to: "posts#nine_summer_fukuoka"
  get "posts/new_nine_summer_fukuoka", to: "posts#new_nine_summer_fukuoka"
  post "posts/new_nine_summer_fukuoka", to: "posts#create_nine_summer_fukuoka"
  get "posts/2019/nine_summer_osaka",to: "posts#nine_summer_osaka"
  get "posts/new_nine_summer_osaka", to: "posts#new_nine_summer_osaka"
  post "posts/new_nine_summer_osaka", to: "posts#create_nine_summer_osaka"
  get "posts/2019/nine_summer_tokyo",to: "posts#nine_summer_tokyo"
  get "posts/new_nine_summer_tokyo", to: "posts#new_nine_summer_tokyo"
  post "posts/new_nine_summer_tokyo", to: "posts#create_nine_summer_tokyo"
  get "posts/2019/nine_under",to: "posts#nine_under"
  get "posts/new_nine_under", to: "posts#new_nine_under"
  post "posts/new_nine_under", to: "posts#create_nine_under"
  get "posts/2019/nine_shanghai",to: "posts#nine_shanghai"
  get "posts/new_nine_shanghai", to: "posts#new_nine_shanghai"
  post "posts/new_nine_shanghai", to: "posts#create_nine_shanghai"
  get "posts/2019/san_yonki",to: "posts#san_yonki"
  get "posts/new_san_yonki", to: "posts#new_san_yonki"
  post "posts/new_san_yonki", to: "posts#create_san_yonki"
  
  #2020
  get "posts/2020", to:"posts#ten"
  get "posts/2020/ten_taipei",to: "posts#ten_taipei"
  get "posts/new_ten_taipei", to: "posts#new_ten_taipei"
  post "posts/new_ten_taipei", to: "posts#create_ten_taipei"
  get "posts/2020/eighth",to: "posts#eighth"
  get "posts/new_eighth", to: "posts#new_eighth"
  post "posts/new_eighth", to: "posts#create_eighth"
  get "posts/2020/ten_under",to: "posts#ten_under"
  get "posts/new_ten_under", to: "posts#new_ten_under"
  post "posts/new_ten_under", to: "posts#create_ten_under"
  
  resources :nogizakas, except: [:destroy]
  

  resources :nogiposts, except: [:show, :create] do
    resources :likes, only: [:create, :destroy]
  end
  resources :images do
    resources :favos, only: [:create, :destroy]
  end

  
  #2012
  get "posts/konno/:id", to: "posts#destroy_konno"
  delete "posts/konno/:id", to: "posts#destroy_konno"
  get "posts/zepptokyo/:id", to: "posts#destroy_zepptokyo"
  delete "posts/zepptokyo/:id", to: "posts#destroy_zepptokyo"

  #2013
  get "posts/first/:id", to: "posts#destroy_first"
  delete "posts/first/:id", to: "posts#destroy_first"
  get "posts/three_summer_sapporo/:id", to: "posts#destroy_three_summer_sapporo"
  delete "posts/three_summer_sapporo/:id", to: "posts#destroy_three_summer_sapporo"
  get "posts/three_summer_fukuoka/:id", to: "posts#destroy_three_summer_fukuoka"
  delete "posts/three_summer_fukuoka/:id", to: "posts#destroy_three_summer_fukuoka"
  get "posts/three_summer_osaka/:id", to: "posts#destroy_three_summer_osaka"
  delete "posts/three_summer_osaka/:id", to: "posts#destroy_three_summer_osaka"
  get "posts/three_summer_nagoya/:id", to: "posts#destroy_three_summer_nagoya"
  delete "posts/three_summer_nagoya/:id", to: "posts#destroy_three_summer_nagoya"
  get "posts/three_summer_tokyo/:id", to: "posts#destroy_three_summer_tokyo"
  delete "posts/three_summer_tokyo/:id", to: "posts#destroy_three_summer_tokyo"
  get "posts/three_summer_final/:id", to: "posts#destroy_three_summer_final"
  delete "posts/three_summer_final/:id", to: "posts#destroy_three_summer_final"
  get "posts/three_xmas/:id", to: "posts#destroy_three_xmas"
  delete "posts/three_xmas/:id", to: "posts#destroy_three_xmas"

  #2014
  get "posts/second/:id", to: "posts#destroy_second"
  delete "posts/second/:id", to: "posts#destroy_second"
  get "posts/four_under/:id", to: "posts#destroy_four_under"
  delete "posts/four_under/:id", to: "posts#destroy_four_under"
  get "posts/four_summer_osaka/:id", to: "posts#destroy_four_summer_osaka"
  delete "posts/four_summer_osaka/:id", to: "posts#destroy_four_summer_osaka"
  get "posts/four_summer_fukuoka/:id", to: "posts#destroy_four_summer_fukuoka"
  delete "posts/four_summer_fukuoka/:id", to: "posts#destroy_four_summer_fukuoka"
  get "posts/four_summer_sendai/:id", to: "posts#destroy_four_summer_sendai"
  delete "posts/four_summer_sendai/:id", to: "posts#destroy_four_summer_sendai"
  get "posts/four_summer_nagoya/:id", to: "posts#destroy_four_summer_nagoya"
  delete "posts/four_summer_nagoya/:id", to: "posts#destroy_four_summer_nagoya"
  get "posts/four_summer_tokyo/:id", to: "posts#destroy_four_summer_tokyo"
  delete "posts/four_summer_tokyo/:id", to: "posts#destroy_four_summer_tokyo"
  get "posts/four_under_second/:id", to: "posts#destroy_four_under_second"
  delete "posts/four_under_second/:id", to: "posts#destroy_four_under_second"
  get "posts/four_under_xmas/:id", to: "posts#destroy_four_under_xmas"
  delete "posts/four_under_xmas/:id", to: "posts#destroy_four_under_xmas"
  get "posts/four_xmas/:id", to: "posts#destroy_four_xmas"
  delete "posts/four_xmas/:id", to: "posts#destroy_four_xmas"

  #2015
  get "posts/third/:id", to: "posts#destroy_third"
  delete "posts/third/:id", to: "posts#destroy_third"
  get "posts/five_summer_sendai/:id", to: "posts#destroy_five_summer_sendai"
  delete "posts/five_summer_sendai/:id", to: "posts#destroy_five_summer_sendai"
  get "posts/five_summer_nagoya/:id", to: "posts#destroy_five_summer_nagoya"
  delete "posts/five_summer_nagoya/:id", to: "posts#destroy_five_summer_nagoya"
  delete "posts/five_summer_hirosima/:id", to: "posts#destroy_five_summer_hirosima"
  get "posts/five_summer_hirosima/:id", to: "posts#destroy_five_summer_hirosima"
  delete "posts/five_summer_fukuoka/:id", to: "posts#destroy_five_summer_fukuoka"
  get "posts/five_summer_fukuoka/:id", to: "posts#destroy_five_summer_fukuoka"
  delete "posts/five_summer_osaka/:id", to: "posts#destroy_five_summer_osaka"
  get "posts/five_summer_osaka/:id", to: "posts#destroy_five_summer_osaka"
  delete "posts/five_summer_tokyo/:id", to: "posts#destroy_five_summer_tokyo"
  get "posts/five_summer_tokyo/:id", to: "posts#destroy_five_summer_tokyo"
  delete "posts/five_under_four/:id", to: "posts#destroy_five_under_four"
  get "posts/five_under_four/:id", to: "posts#destroy_five_under_four"
  delete "posts/five_under_budo/:id", to: "posts#destroy_five_under_budo"
  get "posts/five_under_budo/:id", to: "posts#destroy_five_under_budo"
  delete "posts/five_xmas/:id", to: "posts#destroy_five_xmas"
  get "posts/five_xmas/:id", to: "posts#destroy_five_xmas"
  
  #2016
  delete "posts/seira/:id", to: "posts#destroy_seira"
  get "posts/seira/:id", to: "posts#destroy_seira"
  delete "posts/six_under_tohoku/:id", to: "posts#destroy_six_under_tohoku"
  get "posts/six_under_tohoku/:id", to: "posts#destroy_six_under_tohoku"
  delete "posts/maimai/:id", to: "posts#destroy_maimai"
  get "posts/maimai/:id", to: "posts#destroy_maimai"
  delete "posts/six_summer_osaka/:id", to: "posts#destroy_six_summer_osaka"
  get "posts/six_summer_osaka/:id", to: "posts#destroy_six_summer_osaka"
  delete "posts/six_summer_nagoya/:id", to: "posts#destroy_six_summer_nagoya"
  get "posts/six_summer_nagoya/:id", to: "posts#destroy_six_summer_nagoya"
  delete "posts/six_summer_sendai/:id", to: "posts#destroy_six_summer_sendai"
  get "posts/six_summer_sendai/:id", to: "posts#destroy_six_summer_sendai"
  delete "posts/six_summer_fukuoka/:id", to: "posts#destroy_six_summer_fukuoka"
  get "posts/six_summer_fukuoka/:id", to: "posts#destroy_six_summer_fukuoka"
  delete "posts/six_summer_tokyo/:id", to: "posts#destroy_six_summer_tokyo"
  get "posts/six_summer_tokyo/:id", to: "posts#destroy_six_summer_tokyo"
  delete "posts/six_under_tyugoku/:id", to: "posts#destroy_six_under_tyugoku"
  get "posts/six_under_tyugoku/:id", to: "posts#destroy_six_under_tyugoku"
  delete "posts/six_senbatu_xmas/:id", to: "posts#destroy_six_senbatu_xmas"
  get "posts/six_senbatu_xmas/:id", to: "posts#destroy_six_senbatu_xmas"
  delete "posts/six_under_xmas/:id", to: "posts#destroy_six_under_xmas"
  get "posts/six_under_xmas/:id", to: "posts#destroy_six_under_xmas"

  #2017
  delete "posts/univ/:id", to: "posts#destroy_univ"
  get "posts/univ/:id", to: "posts#destroy_univ"
  delete "posts/fifth/:id", to: "posts#destroy_fifth"
  get "posts/fifth/:id", to: "posts#destroy_fifth"
  delete "posts/under_tokyo/:id", to: "posts#destroy_under_tokyo"
  get "posts/under_tokyo/:id", to: "posts#destroy_under_tokyo"
  delete "posts/sanki/:id", to: "posts#destroy_sanki"
  get "posts/sanki/:id", to: "posts#destroy_sanki"
  delete "posts/seven_summer_tokyo/:id", to: "posts#destroy_seven_summer_tokyo"
  get "posts/seven_summer_tokyo/:id", to: "posts#destroy_seven_summer_tokyo"
  delete "posts/seven_summer_sendai/:id", to: "posts#destroy_seven_summer_sendai"
  get "posts/seven_summer_sendai/:id", to: "posts#destroy_seven_summer_sendai"
  delete "posts/seven_summer_osaka/:id", to: "posts#destroy_seven_summer_osaka"
  get "posts/seven_summer_osaka/:id", to: "posts#destroy_seven_summer_osaka"
  delete "posts/seven_summer_nagoya/:id", to: "posts#destroy_seven_summer_nagoya"
  get "posts/seven_summer_nagoya/:id", to: "posts#destroy_seven_summer_nagoya"
  delete "posts/seven_summer_nigata/:id", to: "posts#destroy_seven_summer_nigata"
  get "posts/seven_summer_nigata/:id", to: "posts#destroy_seven_summer_nigata"
  delete "posts/seven_summer_final/:id", to: "posts#destroy_seven_summer_final"
  get "posts/seven_summer_final/:id", to: "posts#destroy_seven_summer_final"
  delete "posts/seven_under_kyusyu/:id", to: "posts#destroy_seven_under_kyusyu"
  get "posts/seven_under_kyusyu/:id", to: "posts#destroy_seven_under_kyusyu"
  delete "posts/seven_under_kinki/:id", to: "posts#destroy_seven_under_kinki"
  get "posts/seven_under_kinki/:id", to: "posts#destroy_seven_under_kinki"

  #2018
  delete "posts/ikoma/:id", to: "posts#destroy_ikoma"
  get "posts/ikoma/:id", to: "posts#destroy_ikoma"
  delete "posts/under_tyubu/:id", to: "posts#destroy_under_tyubu"
  get "posts/under_tyubu/:id", to: "posts#destroy_under_tyubu"
  delete "posts/sixth/:id", to: "posts#destroy_sixth"
  get "posts/sixth/:id", to: "posts#destroy_sixth"
  delete "posts/eight_summer_fukuoka/:id", to: "posts#destroy_eight_summer_fukuoka"
  get "posts/eight_summer_fukuoka/:id", to: "posts#destroy_eight_summer_fukuoka"
  delete "posts/eight_summer_osaka/:id", to: "posts#destroy_eight_summer_osaka"
  get "posts/eight_summer_osaka/:id", to: "posts#destroy_eight_summer_osaka"
  delete "posts/eight_summer_nagoya/:id", to: "posts#destroy_eight_summer_nagoya"
  get "posts/eight_summer_nagoya/:id", to: "posts#destroy_eight_summer_nagoya"
  delete "posts/eight_summer_sendai/:id", to: "posts#destroy_eight_summer_sendai"
  get "posts/eight_summer_sendai/:id", to: "posts#destroy_eight_summer_sendai"
  delete "posts/under_hokkaido/:id", to: "posts#destroy_under_hokkaido"
  get "posts/under_hokkaido/:id", to: "posts#destroy_under_hokkaido"
  delete "posts/eight_shanghai/:id", to: "posts#destroy_eight_shanghai"
  get "posts/eight_shanghai/:id", to: "posts#destroy_eight_shanghai"
  delete "posts/waka/:id", to: "posts#destroy_waka"
  get "posts/waka/:id", to: "posts#destroy_waka"
  delete "posts/under_kanto/:id", to: "posts#destroy_under_kanto"
  get "posts/under_kanto/:id", to: "posts#destroy_under_kanto"

  #2019
  delete "posts/nine_taipei/:id", to: "posts#destroy_nine_taipei"
  get "posts/nine_taipei/:id", to: "posts#destroy_nine_taipei"
  delete "posts/seventh/:id", to: "posts#destroy_seventh"
  get "posts/seventh/:id", to: "posts#destroy_seventh"
  delete "posts/misa/:id", to: "posts#destroy_misa"
  get "posts/misa/:id", to: "posts#destroy_misa"
  delete "posts/sing_out/:id", to: "posts#destroy_sing_out"
  get "posts/sing_out/:id", to: "posts#destroy_sing_out"
  delete "posts/nine_summer_nagoya/:id", to: "posts#destroy_nine_summer_nagoya"
  get "posts/nine_summer_nagoya/:id", to: "posts#destroy_nine_summer_nagoya"
  delete "posts/nine_summer_fukuoka/:id", to: "posts#destroy_nine_summer_fukuoka"
  get "posts/nine_summer_fukuoka/:id", to: "posts#destroy_nine_summer_fukuoka"
  delete "posts/nine_summer_osaka/:id", to: "posts#destroy_nine_summer_osaka"
  get "posts/nine_summer_osaka/:id", to: "posts#destroy_nine_summer_osaka"
  delete "posts/nine_summer_tokyo/:id", to: "posts#destroy_nine_summer_tokyo"
  get "posts/nine_summer_tokyo/:id", to: "posts#destroy_nine_summer_tokyo"
  delete "posts/nine_under/:id", to: "posts#destroy_nine_under"
  get "posts/nine_under/:id", to: "posts#destroy_nine_under"
  delete "posts/nine_shanghai/:id", to: "posts#destroy_nine_shanghai"
  get "posts/nine_shanghai/:id", to: "posts#destroy_nine_shanghai"
  delete "posts/san_yonki/:id", to: "posts#destroy_san_yonki"
  get "posts/san_yonki/:id", to: "posts#destroy_san_yonki"

  #2020
  delete "posts/ten_taipei/:id", to: "posts#destroy_ten_taipei"
  get "posts/ten_taipei/:id", to: "posts#destroy_ten_taipei"
  delete "posts/eighth/:id", to: "posts#destroy_eighth"
  get "posts/eighth/:id", to: "posts#destroy_eighth"
  delete "posts/ten_under/:id", to: "posts#destroy_ten_under"
  get "posts/ten_under/:id", to: "posts#destroy_ten_under"



  get "nogizakas/delete/:id", to: "nogizakas#destroy"
  post "nogizakas/delete/:id", to: "nogizakas#destroy"
  get "nogiposts/:id", to: "nogiposts#destroy"
 

  
  
  
end


  

  


  #get '/login', to: 'sessions#new'
  #post '/login', to: 'sessions#create'
  #delete '/logout', to: 'sessions#destroy'
  #namespace :admin do
    #resources :users
  #end
  #root to: "tasks#index"
  #resources :tasks do
    #post :confirm, action: :confirm_new, on: :new
    #post :import, on: :collection
  #end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

